apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
spec:
  replicas: 1
  selector:
    matchLabels:
  template:
    metadata:
      labels:
    spec:
      containers:
          imagePullPolicy: IfNotPresent
          ports: