apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminserver
  labels:
    app: adminserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminserver
  template:
    metadata:
      labels:
        app: adminserver
    spec:
      containers:
        - name: adminservercontainer
          image: itamexpertsregistry.azurecr.io/adminserver:v48
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: "dev"