apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminserver
  labels:
    app: adminserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: adminserver
  template:
    metadata:
      labels:
        app: adminserver
    spec:
      containers:
        - name: adminservercontainer
          image: adminservertest:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8082