apiVersion: v1
kind: Service
metadata:
  name: adminservertest-service
spec:
  selector:
    app: adminservertest    # This should match the label on your Pod
  ports:
    - protocol: TCP
      port: 8083             # The port your application is exposed on internally
      targetPort: 8090       # The port on the container
      nodePort: 30188     # The port on the node (external port)
  type: LoadBalancer